"""empty message

Revision ID: 75a95235909c
Revises: de0802062454
Create Date: 2025-05-04 03:14:27.913405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "75a95235909c"
down_revision: Union[str, None] = "de0802062454"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("stock_pharmacy_id_fkey", "stock", type_="foreignkey")
    op.drop_column("stock", "pharmacy_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stock",
        sa.Column("pharmacy_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "stock_pharmacy_id_fkey", "stock", "pharmacy", ["pharmacy_id"], ["id"]
    )
    # ### end Alembic commands ###
