"""alter model medicine to include quantity field

Revision ID: 80ac3dc5e22e
Revises: 75a95235909c
Create Date: 2025-05-06 10:36:20.278740

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "80ac3dc5e22e"
down_revision: Union[str, None] = "75a95235909c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("medicine", sa.Column("quantity", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("medicine", "quantity")
    # ### end Alembic commands ###
