"""did fields nullable

Revision ID: e0991471c8bb
Revises: 6564416ef7a0
Create Date: 2025-05-07 22:04:04.461637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0991471c8bb'
down_revision: Union[str, None] = '6564416ef7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresspharmacy', 'street',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('addresspharmacy', 'neighborhood',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('addresspharmacy', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('addresspharmacy', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('addresspharmacy', 'state',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('addresspharmacy', 'city',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('addresspharmacy', 'neighborhood',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('addresspharmacy', 'street',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
